In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('2565-3-租赁分层.csv')

In [3]:
X = df.iloc[:, 1:-1]

In [4]:
X.shape[0]

29

In [5]:
# import data from 2565-3-租赁分层.csv
df = pd.read_csv('2565-3-租赁分层.csv')
# Remove data from df where '拨备覆盖率(%)' column value is missing
df = df.dropna(subset=['拨备覆盖率(%)'])


X = df.iloc[:, 3:-1]
result = df['分层结果']
# normalize X
X = (X - X.mean()) / X.std()

In [12]:
y1 = np.where(result == '第一梯队', 1, 0)
y2 = np.where(result == '第二梯队', 1, 0)
y3 = np.where(result == '第三梯队', 1, 0)
y4 = np.where(result == '第四梯队', 1, 0)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2)

In [10]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [11]:
y_test

array([1, 1, 0, 0, 0, 1])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2)

In [15]:
y_test

array([1, 1, 0, 1, 0, 0])

In [16]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2)

In [19]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [20]:
y_test

array([0, 0, 0, 0, 1, 0])

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y4, test_size=0.2)
print(y_train)
print(y_test)

[0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0]


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

array([0, 0, 0, 0, 0, 0])

In [33]:
'第' + str(3) + '梯队'

'第3梯队'

In [36]:
k = 2
'第{}梯队'.format(k)

'第2梯队'

In [2]:
import numpy as np

In [9]:
m = np.zeros((2,2))
# prepend one column to m 
m = np.insert(m, 0, 1, axis=1)
m

array([[1., 0., 0.],
       [1., 0., 0.]])